-- CreateEnum
CREATE TYPE "CameraMoveType" AS ENUM ('SLOW_PUSH', 'SLOW_PULL', 'PAN_LEFT', 'PAN_RIGHT', 'TRUCK_LEFT', 'TRUCK_RIGHT', 'PEDESTAL_UP', 'PEDESTAL_DOWN', 'ARC', 'ORBIT', 'PARALLAX', 'FOREGROUND_REVEAL', 'DEPTH_PUSH', 'PERSPECTIVE_SHIFT', 'TILT', 'HERO_PUSH', 'REVEAL', 'CRANE_RISE', 'CORNER_REVEAL', 'MICRO_CAMERA_DRIFT', 'DRONE_RISE', 'DRONE_DESCEND', 'DRONE_ORBIT');

-- AlterTable
ALTER TABLE "project_images" ADD COLUMN     "cameraMoveOverride" "CameraMoveType",
ADD COLUMN     "depthMapStorageKey" TEXT,
ADD COLUMN     "foregroundMaskStorageKey" TEXT;
