/**
 * Template thumbnails.
 *
 * Browsing styles by name is useless — every editor's "Luxury Teal" looks
 * different. The thumbnail is generated by the real engine from a canned
 * phrase, so it shows the actual fonts, colours, scale relationships and
 * composition the template will produce, not an illustration of them.
 */

import { ingest } from '../transcript/ingest.js';
import { compose } from '../engine/compose.js';
import { renderFrame } from '../render/svg.js';
import { toCSS, parseColour, mix } from '../core/colour.js';

/**
 * A phrase chosen to exercise all three levels in one frame: two supporting
 * words, one emphasis word and one hero word.
 */
const SPECIMEN = 'This is a rare and architectural home.';

/**
 * @param {import('./schema.js').Template} template
 * @param {{width?: number, height?: number, aspect?: import('../core/types.js').Frame['aspect'], plate?: string}} [opts]
 * @returns {string} SVG
 */
export function renderThumbnail(template, opts = {}) {
  const aspect = opts.aspect ?? '9:16';
  const [aw, ah] = aspect.split(':').map(Number);
  const height = opts.height ?? 960;
  const width = opts.width ?? Math.round((height * aw) / ah);

  const transcript = ingest(SPECIMEN, { format: 'text', wpm: 135 });

  // Force a full house: thumbnails must show the hierarchy even for a style
  // whose density settings would not promote anything in four seconds.
  /** @type {import('../core/types.js').OverrideMap} */
  const overrides = {};
  const words = transcript.words;
  const rare = words.find((w) => /rare/i.test(w.text));
  const arch = words.find((w) => /architectural/i.test(w.text));
  if (rare) overrides[rare.id] = { level: 'emphasis' };
  if (arch) overrides[arch.id] = { level: 'hero' };

  const plan = compose({
    transcript,
    template: { ...template, hierarchy: { ...template.hierarchy, maxWordsPerPhrase: 9, maxLines: 4, captionDensity: 'high' }, motion: { ...template.motion, reveal: 'phrase' } },
    frame: { width, height, fps: 30, aspect, safeArea: false },
    overrides,
  });

  // Sample at a moment where everything is fully on screen.
  const phrase = plan.phrases.find((p) => p.words.some((w) => w.level === 'hero')) ?? plan.phrases[0];
  const time = phrase ? phrase.start + (phrase.end - phrase.start) * 0.55 : 0;

  const plate = opts.plate ?? platePlaceholder(template);
  return renderFrame(plan, { time, plate, scale: 1 });
}

/**
 * A neutral plate derived from the template's own neutral colour, so a
 * luxury style previews on warm near-black and a social style on cool grey
 * rather than every thumbnail sitting on the same slab.
 */
function platePlaceholder(template) {
  const neutral = parseColour(template.colours.neutral);
  return toCSS(mix(neutral, parseColour('#2a2d31'), 0.55));
}

/**
 * A compact strip showing the three levels in isolation — used in the style
 * picker where a full frame is too tall.
 * @param {import('./schema.js').Template} template
 * @returns {string} SVG
 */
export function renderSwatch(template) {
  const W = 420, H = 96;
  const c = template.colours;
  const chip = (x, colour, label) =>
    `<rect x="${x}" y="58" width="26" height="26" rx="4" fill="${colour}" stroke="rgba(255,255,255,0.14)"/>` +
    `<text x="${x + 13}" y="94" font-family="ui-sans-serif,system-ui" font-size="8" fill="#8b9096" text-anchor="middle">${label}</text>`;

  const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;');
  const f = template.fonts;
  const fam = (spec) => `${spec.family.includes(' ') ? `'${spec.family}'` : spec.family}, sans-serif`;
  const wt = { thin: 100, extralight: 200, light: 300, regular: 400, medium: 500, semibold: 600, bold: 700, extrabold: 800, black: 900 };

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">
  <rect width="${W}" height="${H}" fill="${template.colours.neutral}"/>
  <text x="14" y="30" font-family="${fam(f.normal)}" font-size="15" font-weight="${wt[f.normal.weight]}" fill="${c.primary}">${esc('supporting')}</text>
  <text x="104" y="30" font-family="${fam(f.emphasis)}" font-size="17" font-weight="${wt[f.emphasis.weight]}" fill="${c.accent}">${esc('EMPHASIS')}</text>
  <text x="14" y="52" font-family="${fam(f.hero)}" font-size="26" font-weight="${wt[f.hero.weight]}"${f.hero.italic ? ' font-style="italic"' : ''} fill="${c.hero}">${esc('HERO')}</text>
  ${chip(240, c.primary, 'primary')}${chip(276, c.accent, 'accent')}${chip(312, c.secondary, 'second')}${chip(348, c.hero, 'hero')}
  <text x="${W - 12}" y="24" font-family="ui-sans-serif,system-ui" font-size="10" fill="#8b9096" text-anchor="end">${esc(template.name)}</text>
</svg>`;
}
